### ISSUE TITLE
Ambulance teleports to Vinewood when too far away, instead of behind player

### ISSUE THREAD

**Issue by Salzian** [Salzian/FivePD-Medical-Assistance#15]
**Describe the bug**
it would appear that if you get too far away from the ambulance at any point in time, it just teleports away to the same spot up towards Vinewood, not far from the LS Customs garage

**To Reproduce**
Unknown

**Expected behaviour**
The ambulance should teleport a few meters behind the primary officer. This is a safety mechanism in case the ambulance get's stuck and is unable to follow the player.

**Screenshots**
![ambo bug 1](https://user-images.githubusercontent.com/23481219/83607109-ebdddb80-a57a-11ea-9339-4ffa6240f895.png)
![ambo bug 2](https://user-images.githubusercontent.com/23481219/83607121-f13b2600-a57a-11ea-9891-e673996310fb.png)

**Additional context**
https://discord.com/channels/699790258312577054/701512512100761711/717493068106039507
The spawn point of the ambulance bay be Vector.Zero.

**Comment by HB-2012** [comment]
In case you didn't know, the default `World.GetPosition*` methods actually return `Vector3.Zero` if no suitable location could be found. The default game natives have return type `bool`, but the native CitizenFX wrapper hides this. You must manually check whether the game could successfully spawn the vehicle or not, and if not, apply a fallback.
